apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /okonomi-og-gjeld/api/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /okonomi-og-gjeld/api/isReady
    initialDelay: 5
    timeout: 1
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  vault:
    enabled: false
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: api.sanity.io
        - host: cxql1dm9.api.sanity.io
        - host: apicdn.sanity.io
        - host: cxql1dm9.apicdn.sanity.io
        - host: cdn.sanity.io
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
