apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: okonomi-gjeldsradgivning-veiviser
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /api/isReady
    initialDelay: 5
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
  replicas:
    min: 1
    max: 2
  webproxy: true
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  vault:
    enabled: false
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: api.sanity.io
        - host: apicdn.sanity.io
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  env:
    - name: DECORATOR_URL
      value: {{decoratorUrl}}